### ISSUE TITLE
Informações Telefonica

### ISSUE THREAD

**Issue by vterry** [LeoniTeixeira/desafio2-backend#1]
@LeoniTeixeira bom dia.

Poderia remover as informações da telefônica disponíveis no seu .npmrc?

**Comment by LeoniTeixeira** [comment]
Opa tudo bem? 
Eu removi as informações do .npmrc, teria mais infos em algum outro lugar ?

**Comment by vterry** [comment]
Fala Leoni, tudo certo.

Era só no .npmrc mesmo. Muito obrigado :D

Em qua., 22 de jun. de 2022 às 15:55, Leoni Teixeira de Araújo <
***@***.***> escreveu:
